services:
  - type: web
    name: liamgas
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn liamgas.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true